name: build-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: student-fuzzer:latest
        push: false
        load: true
    - uses: addnab/docker-run-action@v3
      with:
        image: student-fuzzer:latest
        run: |
          cp examples/0/bug.py .; timeout 10s python student_fuzzer.py; test $? -eq 219
